---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resource-db
  namespace: ktask
spec:
  serviceName: resource-db
  replicas: 1
  selector:
    matchLabels:
      app: resource-db
  template:
    metadata:
      labels:
        app: resource-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine3.18
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: resource-db-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: resource-db-storage
              mountPath: /var/lib/postgresql/data
            - name: initdb-resource
              mountPath: /docker-entrypoint-initdb.d/init-resource-svc-db.sql
              subPath: init-resource-svc-db.sql
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -p
                - "5432"
            initialDelaySeconds: 25
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -p
                - "5432"
            initialDelaySeconds: 25
            periodSeconds: 10
          startupProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -p
                - "5432"
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 10
      volumes:
        - name: initdb-resource
          configMap:
            name: resource-db-init-config
            defaultMode: 0744
  volumeClaimTemplates:
    - metadata:
        name: resource-db-storage
      spec:
        storageClassName: hostpath
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: song-db
  namespace: ktask
spec:
  serviceName: song-db
  replicas: 1
  selector:
    matchLabels:
      app: song-db
  template:
    metadata:
      labels:
        app: song-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine3.18
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: song-db-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: song-db-storage
              mountPath: /var/lib/postgresql/data
            - name: initdb-song
              mountPath: /docker-entrypoint-initdb.d/init-song-svc-db.sql
              subPath: init-song-svc-db.sql
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -p
                - "5432"
            initialDelaySeconds: 25
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -p
                - "5432"
            initialDelaySeconds: 25
            periodSeconds: 10
          startupProbe:
            exec:
              command:
                - pg_isready
                - -h
                - localhost
                - -p
                - "5432"
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 10
      volumes:
        - name: initdb-song
          configMap:
            name: song-db-init-config
            defaultMode: 0744
  volumeClaimTemplates:
    - metadata:
        name: song-db-storage
      spec:
        storageClassName: hostpath
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Mi
