---
apiVersion: v1
kind: Service
metadata:
  name: song-svc
  namespace: ktask
spec:
  type: ClusterIP
  selector:
    app: song-svc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
