---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: song-svc
  namespace: ktask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: song-svc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: song-svc
    spec:
      containers:
        - name: song-svc
          image: irrisorrimus/song-svc:v1.1
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: song-db-secret
          env:
            - name: SONG_SVC_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-deployment-config
                  key: SONG_SVC_PORT
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 50
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 50
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
